const COMMANDS = {
  help: () => [
    'Available commands:',
    '  help        - Show this help message',
    '  about       - About the developer',
    '  projects    - List projects',
    '  skills      - List skills',
    '  experience  - Work experience',
    '  achievements- Achievements',
    '  contact     - Contact information',
    '  dir         - List files',
    '  cls         - Clear screen',
    '  echo [msg]  - Print a message',
    '  date        - Show current date/time',
    '  ver         - Show version',
    '  color [hex] - Change text color',
    '  matrix      - Enter the matrix',
    '  whoami      - Who are you?',
    '',
  ],

  about: () => [
    '╔══════════════════════════════════════════════════╗',
    '║              ABOUT THE DEVELOPER                 ║',
    '╠══════════════════════════════════════════════════╣',
    '║ Name:    V. William Gladston                     ║',
    '║ Role:    Full-Stack Developer                    ║',
    '║ Focus:   Scalable Web + AI Systems               ║',
    '║ College: BK Birla Institute, Pilani              ║',
    '╚══════════════════════════════════════════════════╝',
    '',
  ],

  projects: () => [
    'Highlighted Projects:',
    '',
    '[1] AI-Powered Code Reviewer',
    '    → MERN + Gemini API',
    '    → Automated code review with AI feedback',
    '    → 200+ evaluations, 40% time reduction',
    '',
    '[2] Real-Time Collaboration App',
    '    → React + Node + WebSocket',
    '    → Live multi-user communication system',
    '',
    '[3] File Sharing Platform',
    '    → Node + MongoDB + Multer',
    '    → Secure links with 24hr expiration',
    '',
    '[4] Bank Transaction System',
    '    → REST APIs + MongoDB',
    '    → 1000+ simulated transactions',
    '',
  ],

  skills: () => [
    'Technical Skills:',
    '',
    'Languages:',
    '  → Python, C++, JavaScript, Java, SQL',
    '',
    'Frontend:',
    '  → React.js',
    '',
    'Backend:',
    '  → Node.js, Express.js',
    '',
    'Databases:',
    '  → MongoDB, MySQL',
    '',
    'Tools:',
    '  → Git, GitHub, Firebase, Postman',
    '',
  ],

  experience: () => [
    'Work Experience:',
    '',
    '[1] Software Development Intern',
    '    Company: Blue Stocks',
    '    Duration: Jun 2025 – Jul 2025',
    '    → Improved backend performance by 25%',
    '    → Reduced API response time by 30%',
    '',
    '[2] AI & Cloud Trainee',
    '    Organization: Edunet Foundation (IBM + AICTE)',
    '    Duration: Jul 2025 – Aug 2025',
    '    → Worked on AI + Cloud implementations',
    '    → Hands-on with IBM Cloud',
    '',
  ],

  achievements: () => [
    'Achievements:',
    '',
    '🏆 GATE 2026 Qualified',
    '🥇 Winner — Ideathon (IEI BITS Pilani 2024)',
    '🥈 2nd Place — Smart India Hackathon 2025',
    '☁️ AWS Cloud Foundations Certified',
    '💼 Goldman Sachs & JP Morgan SE Programs',
    '',
  ],

  contact: () => [
    'Contact Information:',
    '',
    '📧 Email:    williamgladston4@gmail.com',
    '📱 Phone:    +91-7014825243',
    '💼 LinkedIn: linkedin.com/in/williamgladston',
    '💻 GitHub:   github.com/williamgladston',
    '🌐 Portfolio: williamgladston.github.io',
    '',
  ],

  dir: () => [
    ' Directory of C:\\Users\\William\\Portfolio',
    '',
    ' resume.pdf',
    ' projects/',
    ' achievements.txt',
    ' contact.txt',
    '',
  ],

  ver: () => [
    '',
    'Windows XP [Version 5.1.2600] (William OS v2.0)',
    '',
  ],

  whoami: () => [
    'V. William Gladston',
    'Full Stack Developer | AI Enthusiast',
    '',
  ],

  date: () => [new Date().toString(), ''],

  matrix: () => [
    'Wake up, William...',
    'You are building the future...',
    '',
  ],
};